backend:
  name: git-gateway
  branch: main

# 이미지 등 미디어 파일을 저장하고 불러올 경로 설정
media_folder: public/image
public_folder: /image

# collections는 여러 개의 독립된 컬렉션 목록입니다.
collections:
  # 첫 번째 폴더 컬렉션: 17Lf 시리즈
  - name: "docs" # 컬렉션 고유 ID (공백 없이)
    label: "docs" # 관리자 페이지에 표시될 이름
    folder: "docs/" # 이 폴더 안의 모든 마크다운 파일을 관리
    create: true
    slug: "{{slug}}"
    extension: "md"
    nested:
      depth: 100 # 검사할 하위 폴더의 깊이. 100 정도면 사실상 '전체'를 의미합니다.
    # ⬇️ 재사용할 필드 구조를 앵커(&)로 정의합니다.
    summary: "{{title}} ({{slug}})" # 리스트에 제목과 파일명을 표시
    fields: &manual_fields
      - { label: "파일명 (URL에 사용, 영문)", name: "slug", widget: "string" }
      - { label: "매뉴얼 제목", name: "title", widget: "string" }
      - { label: "버전", name: "version", widget: "string", required: false }
      - { label: "최종 수정일", name: "last_updated", widget: "datetime", required: false }
      - { label: "본문", name: "body", widget: "markdown" }

  # 두 번째 폴더 컬렉션: 12Lf 시리즈
  - name: "en"
    label: "en"
    folder: "en/"
    create: true
    slug: "{{slug}}"
    extension: "md"    
    nested:
      depth: 100 # 검사할 하위 폴더의 깊이. 100 정도면 사실상 '전체'를 의미합니다.
    # ⬇️ 위에서 정의한 필드 구조를 별칭(*)으로 재사용합니다.
    summary: "{{title}} ({{slug}})" # 리스트에 제목과 파일명을 표시
    fields: *manual_fields
