backend:
  name: git-gateway
  branch: main

media_folder: public/image
public_folder: /image

collections:

  - name: "17Lf"
    label: "17Lf 시리즈"
    files:
      - name: "manual_17lf"
        label: "mightyZAP 17Lf 사용자 매뉴얼"
        file: "docs/actuator/Mini17Lf/Manual/mightyZAP 17Lf User Manual.md"
        fields:
          - { label: "매뉴얼 제목", name: "title", widget: "string" }
          - { label: "버전", name: "version", widget: "string", required: false }
          - { label: "최종 수정일", name: "last_updated", widget: "datetime", required: false }
          - { label: "본문", name: "body", widget: "markdown" }
      - name: "17Lf Modbus RTU_kor"
        label: "17Lf Modbus RTU_kor"
        file: "docs/actuator/Mini17Lf/Manual/17Lf Modbus RTU_kor.md"
        fields:
          - { label: "매뉴얼 제목", name: "title", widget: "string" }
          - { label: "버전", name: "version", widget: "string", required: false }
          - { label: "최종 수정일", name: "last_updated", widget: "datetime", required: false }
          - { label: "본문", name: "body", widget: "markdown" }