backend:
  name: git-gateway
  branch: main

media_folder: public/image
public_folder: /image

collections:
  - name: "17Lf"
    label: "17Lf 시리즈"
    widget: "rich_text"
    # ⬇️ 표시할 버튼 목록을 직접 추가합니다.
    buttons:
      - "bold"
      - "italic"
      - "link"
      - "heading-one"
      - "heading-two"
      - "bulleted-list"
      - "numbered-list"
      - "quote"
      - "table" # <-- 테이블 버튼을 명시적으로 추가
    files:
      - name: "17Lf Series"
        label: "mightyZAP 17Lf Series"
        folder: "docs/actuator/Mini17Lf/"
        create: true # 관리자 페이지에서 새 문서 생성 기능 활성화
        slug: "{{slug}}" # 파일명을 문서의 'slug' 필드 값으로 자동 생성
        extension: "md" # 파일 확장자
        fields: &manual_fields # 각 파일에 개별적으로 fields 추가
          - { label: "매뉴얼 제목", name: "title", .widget: "rich_text" }
          - { label: "버전", name: "version", .widget: "rich_text", required: false }
          - { label: "최종 수정일", name: "last_updated", widget: "datetime", required: false }
          - { label: "본문", name: "body", widget: "markdown" }

      - name: "12Lf Series"
        label: "mightyZAP 12Lf Series"
        folder: "docs/actuator/Mini12Lf"
        create: true # 관리자 페이지에서 새 문서 생성 기능 활성화
        slug: "{{slug}}" # 파일명을 문서의 'slug' 필드 값으로 자동 생성
        extension: "md" # 파일 확장자
        fields: *manual_fields
      - name: "D7D12L12 Series"
        label: "mightyZAP 17Lf 50mm datasheet"
        folder: "docs/actuator/D7D12L12"
        create: true # 관리자 페이지에서 새 문서 생성 기능 활성화
        slug: "{{slug}}" # 파일명을 문서의 'slug' 필드 값으로 자동 생성
        extension: "md" # 파일 확장자
        fields: *manual_fields
