backend:
  name: git-gateway
  branch: main

media_folder: public/image
public_folder: /image

collections:
  - name: "actuator"
    label: "액추에이터"
    folder: "docs/actuator"
    # ⬇️ 중첩 컬렉션을 활성화하는 핵심 설정입니다.
    nested:
      depth: 2 # 탐색할 하위 폴더의 최대 깊이
    # ⬇️ CMS에서 항목을 클릭했을 때의 경로 규칙
    path: "{{slug}}/index.md" 
    fields: # 모든 문서에 공통으로 적용될 필드
      - { label: "제목", name: "title", widget: "string" }
      - { label: "본문", name: "body", widget: "markdown" }
  - name: "software"
    label: "software"
    folder: "docs/software"
    # ⬇️ 중첩 컬렉션을 활성화하는 핵심 설정입니다.
    nested:
      depth: 2 # 탐색할 하위 폴더의 최대 깊이
    # ⬇️ CMS에서 항목을 클릭했을 때의 경로 규칙
    path: "{{slug}}/index.md" 
    fields: # 모든 문서에 공통으로 적용될 필드
      - { label: "제목", name: "title", widget: "string" }
      - { label: "본문", name: "body", widget: "markdown" }