backend:
  name: git-gateway
  branch: main

media_folder: public/image
public_folder: /image

collections:
  - name: "17Lf"
    label: "17Lf 시리즈"
    files:
      - name: "datasheet_27"
        label: "mightyZAP 17Lf 27mm datasheet"
        file: "docs/actuator/Mini17Lf/Datasheet/17Lf-xxf-27.md"
        fields: # 각 파일에 개별적으로 fields 추가
          - { label: "매뉴얼 제목", name: "title", widget: "string" }
          - { label: "버전", name: "version", widget: "string", required: false }
          - { label: "최종 수정일", name: "last_updated", widget: "datetime", required: false }
          - { label: "본문", name: "body", widget: "markdown" }

      - name: "datasheet_37"
        label: "mightyZAP 17Lf 37mm datasheet"
        file: "docs/actuator/Mini17Lf/Datasheet/17Lf-xxf-37.md"
        fields:
          - { label: "매뉴얼 제목", name: "title", widget: "string" }
          - { label: "버전", name: "version", widget: "string", required: false }
          - { label: "최종 수정일", name: "last_updated", widget: "datetime", required: false }
          - { label: "본문", name: "body", widget: "markdown" }

      - name: "datasheet_50"
        label: "mightyZAP 17Lf 50mm datasheet"
        file: "docs/actuator/Mini17Lf/Datasheet/17Lf-xxf-50.md"
        fields:
          - { label: "매뉴얼 제목", name: "title", widget: "string" }
          - { label: "버전", name: "version", widget: "string", required: false }
          - { label: "최종 수정일", name: "last_updated", widget: "datetime", required: false }
          - { label: "본문", name: "body", widget: "markdown" }

      - name: "datasheet_87"
        label: "mightyZAP 17Lf 87mm datasheet"
        file: "docs/actuator/Mini17Lf/Datasheet/17Lf-xxf-87.md"
        fields:
          - { label: "매뉴얼 제목", name: "title", widget: "string" }
          - { label: "버전", name: "version", widget: "string", required: false }
          - { label: "최종 수정일", name: "last_updated", widget: "datetime", required: false }
          - { label: "본문", name: "body", widget: "markdown" }
          
      - name: "manual_17lf"
        label: "mightyZAP 17Lf 사용자 매뉴얼"
        file: "docs/actuator/Mini17Lf/Manual/mightyZAP 17Lf User Manual_kor.md"
        fields:
          - { label: "매뉴얼 제목", name: "title", widget: "string" }
          - { label: "버전", name: "version", widget: "string", required: false }
          - { label: "최종 수정일", name: "last_updated", widget: "datetime", required: false }
          - { label: "본문", name: "body", widget: "markdown" }
          
      - name: "17Lf Modbus RTU_kor"
        label: "17Lf Modbus RTU_kor"
        file: "docs/actuator/Mini17Lf/Manual/17Lf Modbus RTU_kor.md"
        fields:
          - { label: "매뉴얼 제목", name: "title", widget: "string" }
          - { label: "버전", name: "version", widget: "string", required: false }
          - { label: "최종 수정일", name: "last_updated", widget: "datetime", required: false }
          - { label: "본문", name: "body", widget: "markdown" }