# GitHub 저장소와 연동하고, Netlify의 Git Gateway를 통해 인증합니다.
backend:
  name: git-gateway
  branch: main # 또는 master 등 메인 브랜치 이름

# 미디어(이미지 등) 파일이 저장될 경로와 웹에서 접근할 경로를 지정합니다.
# VitePress의 public 폴더 규칙에 맞추는 것이 좋습니다.
media_folder: "./img"
public_folder: "./img"

# 관리할 콘텐츠의 종류(컬렉션)를 정의합니다.
collections:
  - name: "posts" # 컬렉션의 고유 이름 (영문)
    label: "블로그 게시물" # 관리자 화면에 표시될 이름
    folder: "docs/posts" # 실제 마크다운 파일이 저장된 폴더 경로
    create: true # 새 파일 생성 기능 활성화
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # 파일명 생성 규칙
    fields: # 각 문서에 포함될 필드(메타데이터 및 본문) 정의
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일", name: "date", widget: "datetime" }
      - { label: "태그", name: "tags", widget: "list", required: false }
      - { label: "본문", name: "body", widget: "markdown" }